global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    cluster:     otel-lab
    environment: production

scrape_configs:
  # OTel Collector expone las métricas agregadas de service-a y service-b
  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector-svc:8889"]

  