apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-svc:9090
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
          urlDisplayLabel: "Ver traza en Jaeger"

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-svc:16686
    uid: jaeger
    jsonData:
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: Prometheus