apiVersion: 1

datasources:

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-svc:9090
    isDefault: true

    jsonData:
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
          urlDisplayLabel: "Ver traza en Jaeger"

  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-svc:16686

    jsonData:
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus